# Generated by Django 5.1.2 on 2024-11-06 01:07

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='그룹 이름')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[('Mon', '월'), ('Tue', '화'), ('Wed', '수'), ('Thu', '목'), ('Fri', '금'), ('Sat', '토'), ('Sun', '일')], max_length=3, verbose_name='요일')),
                ('date', models.DateField(null=True, verbose_name='날짜')),
                ('start_time', models.TimeField(default=datetime.time(9, 0), verbose_name='시작 시간')),
                ('end_time', models.TimeField(default=datetime.time(22, 0), verbose_name='종료 시간')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('password', models.CharField(blank=True, max_length=10, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group')),
            ],
        ),
    ]
